services:
  pyspark_notebook:
    container_name: pyspark_notebook
    build: .
    platform: linux/amd64
    volumes:
      - "./spark-data:/home/jovyan/spark-data"
      - "./notebooks:/home/jovyan/work"
    ports:
      - '8080:8080'
      - '8888:8888'   # this port is for jupyter notebook